osx_image: xcode7.3
language: objective-c
script:
- set -o pipefail && xcodebuild -workspace WordPressComKit.xcworkspace -scheme WordPressComKit -sdk iphonesimulator build test ONLY_ACTIVE_ARCH=NO | xcpretty -c
